# Generated by Django 4.2.5 on 2026-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalregistro_usuario_registro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistro',
            name='campos_personalizados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Campos Customizados'),
        ),
        migrations.AddField(
            model_name='registro',
            name='campos_personalizados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Campos Customizados'),
        ),
    ]
